# Generated by Django 5.0.11 on 2025-01-31 14:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='created date')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='modified date')),
                ('user_profile_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='user_profile_id', primary_key=True, serialize=False)),
                ('masked_name', models.CharField(max_length=100, null=True)),
                ('masked_tel_num', models.CharField(max_length=20, null=True)),
                ('birthday', models.DateField(null=True)),
                ('sex', models.IntegerField(null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
    ]
